### ISSUE TITLE
I got _itree not found issue on Win10

### ISSUE THREAD

**Issue by SleepySoft** [juncongmoo/itree#21]
Traceback (most recent call last):
  File "webapp_single.py", line 13, in <module>
    from llama import ModelArgs, Transformer, Tokenizer, LLaMA
  File "C:\Users\sleep\.conda\envs\llama\lib\site-packages\llama\__init__.py", line 17, in <module>
    from .model_single import ModelArgs, Transformer
  File "C:\Users\sleep\.conda\envs\llama\lib\site-packages\llama\model_single.py", line 7, in <module>
    import hiq
  File "C:\Users\sleep\.conda\envs\llama\lib\site-packages\hiq\__init__.py", line 57, in <module>
    from .tree import (
  File "C:\Users\sleep\.conda\envs\llama\lib\site-packages\hiq\tree.py", line 9, in <module>
    import itree
  File "C:\Users\sleep\.conda\envs\llama\lib\site-packages\itree\__init__.py", line 7, in <module>
    import _itree
ModuleNotFoundError: No module named '_itree'

**Comment by zavinator** [comment]
It is not working in Python 3.10.x - the provided pyd depends on python311.dll
It works correctly when installed in Python 3.11...

**Comment by juncongmoo** [comment]
check this: https://github.com/juncongmoo/itree#build-from-source-with-cmake @SleepySoft
